### ISSUE TITLE
Kraken.xbteur does not work

### ISSUE THREAD

**Issue by pangoSE** [polyrabbit/token-ticker#11]
Hi, I could not get xbteur to work even though it is listen here 
https://api.kraken.com/0/public/AssetPairs

**Comment by polyrabbit** [comment]
Sorry for the late reply. I find Kraken names it `XXBTZEUR`. You can try that name.

![image](https://user-images.githubusercontent.com/2657334/76646419-e7b2ab00-6595-11ea-95b6-5ee8cfb40c82.png)
