### ISSUE TITLE
Show specific columns

### ISSUE THREAD

**Issue by billzhong** [polyrabbit/token-ticker#3]
Hi,

Any chance to add this?
Thanks.

**Comment by polyrabbit** [comment]
Do you think the current columns are too noisy, and you want to only show a subset of them?

**Comment by billzhong** [comment]
Yep, I want to show specific columns only.
Actually, I want to display it on my 3.5 inch raspberry pi LCD which only has 480x320px.

**Comment by polyrabbit** [comment]
Sounds reasonable, I'll add this feature later, but not now, got very busy recently.

Or would you mind to help?

**Comment by billzhong** [comment]
Thanks, no hurry. Unfortunately, I am not familiar with Go.

**Comment by polyrabbit** [comment]
I just made a new [release](https://github.com/polyrabbit/token-ticker/releases/tag/v0.3.0) that supports this feature, please try:

```bash
tt -s=Symbol,Price
```

**Comment by billzhong** [comment]
![pi](https://user-images.githubusercontent.com/1644011/46167696-17baa100-c271-11e8-9785-85699f222603.jpeg)
Looks great! Thanks.

**Comment by polyrabbit** [comment]
Closing, and EOS TO THE MOON 🌔!
